#include<iostream.h>
#include<conio.h>
int main()
  {
   int integerType;
   char charType;
   float floatType;
   double doubleType;

   clrscr();
   cout << "Size of int is:" <<  "sizeof(integerType)" << "\n";
   cout << "Size of char is:" << "sizeof(charType)" << "\n";
   cout << "Size of float is:" << "sizeof(floatType)" << "\n";
   cout << "Size of double is:" << "sizeof(doubleType)" << "\n";
   getch();
  }